title: Alpay's Tech Blog
description: A blog about Swift, iOS Development, and more
author: Alpay Calalli
url: "https://alpaycli.github.io"
baseurl: "/alpaycli-blog"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links
github_username: alpaycalalli
# twitter_username: your-twitter-handle
# linkedin_username: your-linkedin-handle

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Alpay Calalli"
      
# Collections
collections:
  - swift
  - ios

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
